---
apiVersion: v1
kind: Service
metadata:
  name: portal-x-backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: main-portal-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-portal-deployment
spec:
  selector:
    matchLabels:
      app: main-portal-backend
  template:
    metadata:
      labels:
        app: main-portal-backend
    spec:
      imagePullSecrets:
        - name: github-registry-auth
      containers:
        - name: backend-springboot
          image: main-backend-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: portal-config
          - secretRef:
              name: portal-fh-secret
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: replaced-kustomize
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: replaced-kustomize
                  key: password
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api


          #          {{- range $key, $value := .Values.application.secrets }}
#          - secretRef:
#              name: {{ $value }}
#          {{- end }}

          # main-portal.main-possible-portal-db.credentials.postgresql.acid.zalan.do