---
apiVersion: v1
kind: Service
metadata:
  name: portal-x-frontend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: main-portal-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-portal-deployment
spec:
  selector:
    matchLabels:
      app: main-portal-frontend
  template:
    metadata:
      labels:
        app: main-portal-frontend
    spec:
      imagePullSecrets:
        - name: github-registry-auth
      containers:
        - name: backend-springboot
          image: main-frontend-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080