apiVersion: v1
kind: Service
metadata:
  name: {{ include "possible-x-edc-portal.fullname" . }}-postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: {{ include "possible-x-edc-portal.fullname" . }}-postgres