#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "possible-x-edc-portal.fullname" . }}-postgres
  labels:
    app: {{ include "possible-x-edc-portal.fullname" . }}-postgres
spec:
  serviceName: "{{ include "possible-x-edc-portal.fullname" . }}-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "possible-x-edc-portal.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "possible-x-edc-portal.fullname" . }}-postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.application.db.image.repository }}:{{ .Values.application.db.image.tag }}"
        imagePullPolicy: {{ .Values.application.db.image.pullPolicy }}
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.application.variables.database.SPRING_DATASOURCE_DATABASE }}"
        - name: POSTGRES_USER
          value: "{{ .Values.application.variables.database.SPRING_DATASOURCE_USERNAME }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.application.secrets.database }}
              key: SPRING_DATASOURCE_PASSWORD
        volumeMounts:
        - name: {{ include "possible-x-edc-portal.fullname" . }}-postgres-storage
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: {{ include "possible-x-edc-portal.fullname" . }}-postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi