apiVersion: v1
kind: Service
metadata:
  name: {{ include "possible-x-edc-portal.fullname" . }}
  labels:
    {{- include "possible-x-edc-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "possible-x-edc-portal.selectorLabels" . | nindent 4 }}
