apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edc-dev
namePrefix: main-


resources:
  - ../../base


images:
  - name: main-backend-image
    newName: ghcr.io/possible-x/main-portal-backend
    newTag: 7260d5bdcf289b88a7dee8be1f36d33ce5f8c775
  - name: main-frontend-image
    newName: ghcr.io/possible-x/main-portal-frontend
    newTag: 7260d5bdcf289b88a7dee8be1f36d33ce5f8c775

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backend-portal-deployment
    patch: |
      - op: replace #action
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name #resouirce we want to change
        value: main-portal.main-possible-portal-db.credentials.postgresql.acid.zalan.do
      - op: replace #action
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name #resouirce we want to change
        value: main-portal.main-possible-portal-db.credentials.postgresql.acid.zalan.do
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: portal-x-ingress
    patch: |
      - op: replace #action
        path: /spec/rules/0/host
        value: portal.dev.possible-x.de
      - op: replace #action
        path: /spec/tls/0/hosts/0
        value: portal.dev.possible-x.de
      - op: replace #action
        path: /spec/tls/0/secretName
        value: portal-x-tls-secret


configMapGenerator:
  - name: portal-config
    literals:
      - SPRING_DATASOURCE_DATABASE=portal
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-possible-portal-db/portal
      - SPRING_DATASOURCE_USERNAME=admin
      - DAPSSERVER_URL_EXTERNAL=https://daps.int.possible-x.de/auth
      - DAPSSERVER_URL_INTERNAL=http://daps-daps-server:4567
      - DIDWEBSERVICE_BASEURL=http://did-web-service:8080
      - DIDWEBSERVICE_IGNORESSL="false"
      - FH_CATALOG_URL=https://hub.catalog.dev.possible-x.de/
      - SDCREATIONWIZARDAPI_BASEURL=https://sd-creation-wizard.dev.possible-x.de
      - SPRING_PROFILES_ACTIVE=dev


