spring:
  application:
    name: possible-x-portal

server:
  port: 8081

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

sd-creation-wizard-api:
  base-url: http://localhost:8085