#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

spring:
  application:
    name: possible-x-portal
  datasource:
    url: "jdbc:postgresql://localhost:5432/possibleportal"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    admin:
      username: admin
      password: admin

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

sd-creation-wizard-api:
  base-url: http://localhost:8085

daps-server:
  url:
    internal: http://localhost:4567
    external: http://localhost:4567

did-web-service:
  base-url: https://localhost:4443
  ignore-ssl: true

fh:
  catalog:
    ui-url: https://possible.fokus.fraunhofer.de/
    url: url
    secret-key: secret

version.no: "1.0.0"

version.date: "2024-12-31"